FROM bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8

# Switch to root
# USER root

# # Set JAVA_HOME (Java 8 is already installed in this image)

# ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
# ENV PATH $JAVA_HOME/bin:$PATH

# # Set YARN/HDFS user environment variables
# ENV HADOOP_SECURE_DN_USER=root
# ENV YARN_RESOURCEMANAGER_USER=root
# ENV HDFS_NAMENODE_USER=root
# ENV HDFS_DATANODE_USER=root
# ENV HDFS_SECONDARYNAMENODE_USER=root
# ENV YARN_NODEMANAGER_USER=root

# # Start services
# RUN echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' >> ~/.bashrc
# RUN source ~/.bashrc