global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Internal Prometheus port
  
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # cAdvisor's default internal port
  
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']  